import type { CatalogMetric } from "@/lib/types";

export const catalog: CatalogMetric[] = [
  {
    id: "os.cpu.util",
    source: "os",
    group: "CPU",
    name: "Загрузка CPU",
    description: "Доля времени, когда процессоры были заняты. Основной индикатор нагрузки ОС.",
    perfmonPath: "\\Processor Information(_Total)\\% Processor Time",
    zabbixPerfKey: `perf_counter_en["\\Processor Information(_Total)\\% Processor Time"]`,
    zabbixOfficialKey: "system.cpu.util",
    jsonPath: '$.values["os.cpu.util"]',
    unit: "%",
    warn: { op: "gt", value: 80, note: "устойчиво выше 80% в течение нескольких минут" },
    crit: { op: "gt", value: 95, note: "процессорный голод" },
  },
  {
    id: "os.cpu.privileged",
    source: "os",
    group: "CPU",
    name: "CPU privileged time",
    description: "Время в режиме ядра: драйверы, DPC, прерывания. Высокое значение при умеренной пользовательской нагрузке — признак проблем ядра/ввода-вывода.",
    perfmonPath: "\\Processor Information(_Total)\\% Privileged Time",
    zabbixPerfKey: `perf_counter_en["\\Processor Information(_Total)\\% Privileged Time"]`,
    zabbixOfficialKey: `perf_counter_en["\\Processor Information(_Total)\\% Privileged Time"]`,
    jsonPath: '$.values["os.cpu.privileged"]',
    unit: "%",
    warn: { op: "gt", value: 30, note: "ядро занимает слишком много CPU" },
  },
  {
    id: "os.cpu.user",
    source: "os",
    group: "CPU",
    name: "CPU user time",
    description: "Время в пользовательском режиме — обычно SQL Server, приложения.",
    perfmonPath: "\\Processor Information(_Total)\\% User Time",
    zabbixPerfKey: `perf_counter_en["\\Processor Information(_Total)\\% User Time"]`,
    zabbixOfficialKey: `perf_counter_en["\\Processor Information(_Total)\\% User Time"]`,
    jsonPath: '$.values["os.cpu.user"]',
    unit: "%",
  },
  {
    id: "os.cpu.interrupt",
    source: "os",
    group: "CPU",
    name: "CPU interrupt time",
    description: "Время на аппаратные прерывания. Выше ~20% часто указывает на сетевой или дисковый адаптер.",
    perfmonPath: "\\Processor Information(_Total)\\% Interrupt Time",
    zabbixPerfKey: `perf_counter_en["\\Processor Information(_Total)\\% Interrupt Time"]`,
    zabbixOfficialKey: `perf_counter_en["\\Processor Information(_Total)\\% Interrupt Time"]`,
    jsonPath: '$.values["os.cpu.interrupt"]',
    unit: "%",
    warn: { op: "gt", value: 10, note: "возможны проблемы железа/драйверов" },
  },
  {
    id: "os.cpu.dpc",
    source: "os",
    group: "CPU",
    name: "CPU DPC time",
    description: "Отложенные вызовы процедур. Рост вместе с interrupt time — сеть или диск.",
    perfmonPath: "\\Processor Information(_Total)\\% DPC Time",
    zabbixPerfKey: `perf_counter_en["\\Processor Information(_Total)\\% DPC Time"]`,
    zabbixOfficialKey: `perf_counter_en["\\Processor Information(_Total)\\% DPC Time"]`,
    jsonPath: '$.values["os.cpu.dpc"]',
    unit: "%",
  },
  {
    id: "os.cpu.queue",
    source: "os",
    group: "CPU",
    name: "Processor Queue Length",
    description: "Потоки в очереди готовых к выполнению. Ориентир: не больше числа ядер × 2.",
    perfmonPath: "\\System\\Processor Queue Length",
    zabbixPerfKey: `perf_counter_en["\\System\\Processor Queue Length"]`,
    zabbixOfficialKey: `perf_counter_en["\\System\\Processor Queue Length"]`,
    jsonPath: '$.values["os.cpu.queue"]',
    unit: "count",
    warn: { op: "gt", value: 8, note: "очередь больше типичного запаса ядер" },
  },
  {
    id: "os.system.context_switches",
    source: "os",
    group: "Система",
    name: "Context Switches/sec",
    description: "Переключения контекста. Резкий рост при высокой нагрузке — конкуренция потоков.",
    perfmonPath: "\\System\\Context Switches/sec",
    zabbixPerfKey: `perf_counter_en["\\System\\Context Switches/sec"]`,
    zabbixOfficialKey: `perf_counter_en["\\System\\Context Switches/sec"]`,
    jsonPath: '$.values["os.system.context_switches"]',
    unit: "/sec",
  },
  {
    id: "os.system.threads",
    source: "os",
    group: "Система",
    name: "Threads",
    description: "Число потоков всех процессов.",
    perfmonPath: "\\System\\Threads",
    zabbixPerfKey: `perf_counter_en["\\System\\Threads"]`,
    zabbixOfficialKey: `perf_counter_en["\\System\\Threads"]`,
    jsonPath: '$.values["os.system.threads"]',
    unit: "count",
  },
  {
    id: "os.memory.available_mbytes",
    source: "os",
    group: "Память",
    name: "Available MBytes",
    description: "Свободная физическая память. Для SQL Server оставляйте запас, иначе начнётся paging.",
    perfmonPath: "\\Memory\\Available MBytes",
    zabbixPerfKey: `perf_counter_en["\\Memory\\Available MBytes"]`,
    zabbixOfficialKey: "vm.memory.size[available]",
    jsonPath: '$.values["os.memory.available_mbytes"]',
    unit: "MB",
    warn: { op: "lt", value: 512, note: "мало свободной RAM" },
    crit: { op: "lt", value: 128, note: "ОС начнёт вытеснять в pagefile" },
  },
  {
    id: "os.memory.committed_pct",
    source: "os",
    group: "Память",
    name: "% Committed Bytes In Use",
    description: "Доля commit charge от лимита. Рост к 100% — риск нехватки commit limit.",
    perfmonPath: "\\Memory\\% Committed Bytes In Use",
    zabbixPerfKey: `perf_counter_en["\\Memory\\% Committed Bytes In Use"]`,
    zabbixOfficialKey: "vm.memory.util",
    jsonPath: '$.values["os.memory.committed_pct"]',
    unit: "%",
    warn: { op: "gt", value: 80, note: "commit limit заполняется" },
    crit: { op: "gt", value: 95, note: "близко к исчерпанию виртуальной памяти" },
  },
  {
    id: "os.memory.pages_sec",
    source: "os",
    group: "Память",
    name: "Pages/sec",
    description: "Жёсткие page fault: чтение/запись страниц на диск. Высокое значение — нехватка RAM.",
    perfmonPath: "\\Memory\\Pages/sec",
    zabbixPerfKey: `perf_counter_en["\\Memory\\Pages/sec"]`,
    zabbixOfficialKey: `perf_counter_en["\\Memory\\Pages/sec"]`,
    jsonPath: '$.values["os.memory.pages_sec"]',
    unit: "/sec",
    warn: { op: "gt", value: 200, note: "paging уже заметен" },
    crit: { op: "gt", value: 1000, note: "типичный порог шаблона Zabbix" },
  },
  {
    id: "os.memory.page_faults_sec",
    source: "os",
    group: "Память",
    name: "Page Faults/sec",
    description: "Все page fault, включая soft. Сами по себе не страшны; смотрите Pages/sec.",
    perfmonPath: "\\Memory\\Page Faults/sec",
    zabbixPerfKey: `perf_counter_en["\\Memory\\Page Faults/sec"]`,
    zabbixOfficialKey: `perf_counter_en["\\Memory\\Page Faults/sec"]`,
    jsonPath: '$.values["os.memory.page_faults_sec"]',
    unit: "/sec",
  },
  {
    id: "os.memory.pool_nonpaged",
    source: "os",
    group: "Память",
    name: "Pool Nonpaged Bytes",
    description: "Невыгружаемый пул ядра. Постоянный рост — возможная утечка драйвера.",
    perfmonPath: "\\Memory\\Pool Nonpaged Bytes",
    zabbixPerfKey: `perf_counter_en["\\Memory\\Pool Nonpaged Bytes"]`,
    zabbixOfficialKey: `perf_counter_en["\\Memory\\Pool Nonpaged Bytes"]`,
    jsonPath: '$.values["os.memory.pool_nonpaged"]',
    unit: "bytes",
  },
  {
    id: "os.memory.free_pte",
    source: "os",
    group: "Память",
    name: "Free System Page Table Entries",
    description: "Свободные PTE. Ниже 5000 — классический признак утечки/исчерпания.",
    perfmonPath: "\\Memory\\Free System Page Table Entries",
    zabbixPerfKey: `perf_counter_en["\\Memory\\Free System Page Table Entries"]`,
    zabbixOfficialKey: `perf_counter_en["\\Memory\\Free System Page Table Entries"]`,
    jsonPath: '$.values["os.memory.free_pte"]',
    unit: "count",
    warn: { op: "lt", value: 5000, note: "порог шаблона Windows by Zabbix agent" },
  },
  {
    id: "os.paging.usage",
    source: "os",
    group: "Память",
    name: "Paging File % Usage",
    description: "Заполнение pagefile. Высокое значение вместе с Pages/sec — нехватка RAM.",
    perfmonPath: "\\Paging File(_Total)\\% Usage",
    zabbixPerfKey: `perf_counter_en["\\Paging File(_Total)\\% Usage"]`,
    zabbixOfficialKey: `perf_counter_en["\\Paging File(_Total)\\% Usage"]`,
    jsonPath: '$.values["os.paging.usage"]',
    unit: "%",
    warn: { op: "gt", value: 50, note: "pagefile активно используется" },
  },
  {
    id: "os.disk.reads_sec",
    source: "os",
    group: "Диск",
    name: "Disk Reads/sec (_Total)",
    description: "Чтения с физических дисков. Для SQL смотрите вместе с Page reads/sec.",
    perfmonPath: "\\PhysicalDisk(_Total)\\Disk Reads/sec",
    zabbixPerfKey: `perf_counter_en["\\PhysicalDisk(_Total)\\Disk Reads/sec",60]`,
    zabbixOfficialKey: `perf_counter_en["\\PhysicalDisk({#DEVNAME})\\Disk Reads/sec",60]`,
    jsonPath: '$.values["os.disk.reads_sec"]',
    unit: "/sec",
  },
  {
    id: "os.disk.writes_sec",
    source: "os",
    group: "Диск",
    name: "Disk Writes/sec (_Total)",
    description: "Записи на физические диски.",
    perfmonPath: "\\PhysicalDisk(_Total)\\Disk Writes/sec",
    zabbixPerfKey: `perf_counter_en["\\PhysicalDisk(_Total)\\Disk Writes/sec",60]`,
    zabbixOfficialKey: `perf_counter_en["\\PhysicalDisk({#DEVNAME})\\Disk Writes/sec",60]`,
    jsonPath: '$.values["os.disk.writes_sec"]',
    unit: "/sec",
  },
  {
    id: "os.disk.queue",
    source: "os",
    group: "Диск",
    name: "Current Disk Queue Length",
    description: "Текущая очередь диска. Длительная очередь > числа шпинделей/очереди SSD — насыщение.",
    perfmonPath: "\\PhysicalDisk(_Total)\\Current Disk Queue Length",
    zabbixPerfKey: `perf_counter_en["\\PhysicalDisk(_Total)\\Current Disk Queue Length",60]`,
    zabbixOfficialKey: `perf_counter_en["\\PhysicalDisk({#DEVNAME})\\Current Disk Queue Length",60]`,
    jsonPath: '$.values["os.disk.queue"]',
    unit: "count",
    warn: { op: "gt", value: 4, note: "диск не успевает" },
  },
  {
    id: "os.disk.idle",
    source: "os",
    group: "Диск",
    name: "% Idle Time",
    description: "Доля времени простоя диска. Утилизация ≈ 100 − Idle. Низкий idle — диск занят.",
    perfmonPath: "\\PhysicalDisk(_Total)\\% Idle Time",
    zabbixPerfKey: `perf_counter_en["\\PhysicalDisk(_Total)\\% Idle Time",60]`,
    zabbixOfficialKey: `perf_counter_en["\\PhysicalDisk({#DEVNAME})\\% Idle Time",60]`,
    jsonPath: '$.values["os.disk.idle"]',
    unit: "%",
    warn: { op: "lt", value: 20, note: "диск почти не простаивает" },
  },
  {
    id: "os.disk.avg_read_sec",
    source: "os",
    group: "Диск",
    name: "Avg. Disk sec/Read",
    description: "Средняя задержка чтения. Для SSD обычно < 5–10 мс, для SQL log — ещё ниже.",
    perfmonPath: "\\PhysicalDisk(_Total)\\Avg. Disk sec/Read",
    zabbixPerfKey: `perf_counter_en["\\PhysicalDisk(_Total)\\Avg. Disk sec/Read",60]`,
    zabbixOfficialKey: `perf_counter_en["\\PhysicalDisk({#DEVNAME})\\Avg. Disk sec/Read",60]`,
    jsonPath: '$.values["os.disk.avg_read_sec"]',
    unit: "sec",
    warn: { op: "gt", value: 0.02, note: "> 20 мс — диск тормозит чтение" },
    crit: { op: "gt", value: 0.05, note: "> 50 мс — серьёзная задержка" },
  },
  {
    id: "os.disk.avg_write_sec",
    source: "os",
    group: "Диск",
    name: "Avg. Disk sec/Write",
    description: "Средняя задержка записи. Критично для transaction log SQL Server.",
    perfmonPath: "\\PhysicalDisk(_Total)\\Avg. Disk sec/Write",
    zabbixPerfKey: `perf_counter_en["\\PhysicalDisk(_Total)\\Avg. Disk sec/Write",60]`,
    zabbixOfficialKey: `perf_counter_en["\\PhysicalDisk({#DEVNAME})\\Avg. Disk sec/Write",60]`,
    jsonPath: '$.values["os.disk.avg_write_sec"]',
    unit: "sec",
    warn: { op: "gt", value: 0.02, note: "> 20 мс на запись" },
    crit: { op: "gt", value: 0.05, note: "лог SQL будет ждать flush" },
  },
  {
    id: "mssql.buffer_cache_hit_ratio",
    source: "mssql",
    group: "Buffer Manager",
    name: "Buffer cache hit ratio",
    description: "Доля страниц, найденных в buffer pool без чтения с диска. На здоровом OLTP обычно > 98–99%.",
    perfmonPath: "\\SQLServer:Buffer Manager\\Buffer cache hit ratio",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Buffer Manager\\Buffer cache hit ratio"]`,
    zabbixOfficialKey: "mssql.buffer_cache_hit_ratio",
    jsonPath: '$.values["mssql.buffer_cache_hit_ratio"]',
    unit: "%",
    warn: { op: "lt", value: 97, note: "кэш уже не держит рабочий набор" },
    crit: { op: "lt", value: 90, note: "сильное давление на buffer pool" },
  },
  {
    id: "mssql.page_life_expectancy",
    source: "mssql",
    group: "Buffer Manager",
    name: "Page life expectancy",
    description: "Сколько секунд страница живёт в buffer pool. Смотрите резкие провалы относительно своего baseline, а не фиксированные 300 с.",
    perfmonPath: "\\SQLServer:Buffer Manager\\Page life expectancy",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Buffer Manager\\Page life expectancy"]`,
    zabbixOfficialKey: "mssql.page_life_expectancy",
    jsonPath: '$.values["mssql.page_life_expectancy"]',
    unit: "sec",
    warn: { op: "lt", value: 1000, note: "страницы вытесняются быстрее обычного" },
    crit: { op: "lt", value: 300, note: "классический аварийный порог" },
  },
  {
    id: "mssql.lazy_writes_sec",
    source: "mssql",
    group: "Buffer Manager",
    name: "Lazy writes/sec",
    description: "Lazy writer сбрасывает грязные страницы, чтобы освободить буферы. В норме около нуля; устойчиво > 20 — давление памяти.",
    perfmonPath: "\\SQLServer:Buffer Manager\\Lazy writes/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Buffer Manager\\Lazy writes/sec"]`,
    zabbixOfficialKey: "mssql.lazy_writes_sec.rate",
    jsonPath: '$.values["mssql.lazy_writes_sec"]',
    unit: "/sec",
    warn: { op: "gt", value: 20, note: "lazy writer работает слишком часто" },
  },
  {
    id: "mssql.checkpoint_pages_sec",
    source: "mssql",
    group: "Buffer Manager",
    name: "Checkpoint pages/sec",
    description: "Страницы, сбрасываемые checkpoint. Всплески нормальны; постоянный высокий фон — много грязных страниц.",
    perfmonPath: "\\SQLServer:Buffer Manager\\Checkpoint pages/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Buffer Manager\\Checkpoint pages/sec"]`,
    zabbixOfficialKey: "mssql.checkpoint_pages_sec.rate",
    jsonPath: '$.values["mssql.checkpoint_pages_sec"]',
    unit: "/sec",
  },
  {
    id: "mssql.page_reads_sec",
    source: "mssql",
    group: "Buffer Manager",
    name: "Page reads/sec",
    description: "Физические чтения страниц БД. Высокое значение при низком hit ratio — нехватка памяти или плохие планы.",
    perfmonPath: "\\SQLServer:Buffer Manager\\Page reads/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Buffer Manager\\Page reads/sec"]`,
    zabbixOfficialKey: "mssql.page_reads_sec.rate",
    jsonPath: '$.values["mssql.page_reads_sec"]',
    unit: "/sec",
    warn: { op: "gt", value: 90, note: "много физических чтений" },
  },
  {
    id: "mssql.page_writes_sec",
    source: "mssql",
    group: "Buffer Manager",
    name: "Page writes/sec",
    description: "Физические записи страниц БД.",
    perfmonPath: "\\SQLServer:Buffer Manager\\Page writes/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Buffer Manager\\Page writes/sec"]`,
    zabbixOfficialKey: "mssql.page_writes_sec.rate",
    jsonPath: '$.values["mssql.page_writes_sec"]',
    unit: "/sec",
  },
  {
    id: "mssql.free_list_stalls_sec",
    source: "mssql",
    group: "Buffer Manager",
    name: "Free list stalls/sec",
    description: "Запросы, которые ждали свободную страницу в buffer pool. Любое устойчивое значение > 0 — нехватка буферов.",
    perfmonPath: "\\SQLServer:Buffer Manager\\Free list stalls/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Buffer Manager\\Free list stalls/sec"]`,
    zabbixOfficialKey: "mssql.free_list_stalls_sec.rate",
    jsonPath: '$.values["mssql.free_list_stalls_sec"]',
    unit: "/sec",
    warn: { op: "gt", value: 0, note: "есть ожидание свободных буферов" },
  },
  {
    id: "mssql.batch_requests_sec",
    source: "mssql",
    group: "SQL Statistics",
    name: "Batch Requests/sec",
    description: "Пакетов T-SQL в секунду. Главный индикатор полезной работы инстанса. Используйте как знаменатель для компиляций и сканов.",
    perfmonPath: "\\SQLServer:SQL Statistics\\Batch Requests/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:SQL Statistics\\Batch Requests/sec"]`,
    zabbixOfficialKey: "mssql.batch_requests_sec.rate",
    jsonPath: '$.values["mssql.batch_requests_sec"]',
    unit: "/sec",
  },
  {
    id: "mssql.sql_compilations_sec",
    source: "mssql",
    group: "SQL Statistics",
    name: "SQL Compilations/sec",
    description: "Компиляции планов. Высокая доля к Batch Requests — слишком много ad hoc.",
    perfmonPath: "\\SQLServer:SQL Statistics\\SQL Compilations/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:SQL Statistics\\SQL Compilations/sec"]`,
    zabbixOfficialKey: "mssql.sql_compilations_sec.rate",
    jsonPath: '$.values["mssql.sql_compilations_sec"]',
    unit: "/sec",
  },
  {
    id: "mssql.sql_recompilations_sec",
    source: "mssql",
    group: "SQL Statistics",
    name: "SQL Re-Compilations/sec",
    description: "Перекомпиляции. Должны быть близки к нулю относительно compilations.",
    perfmonPath: "\\SQLServer:SQL Statistics\\SQL Re-Compilations/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:SQL Statistics\\SQL Re-Compilations/sec"]`,
    zabbixOfficialKey: "mssql.sql_recompilations_sec.rate",
    jsonPath: '$.values["mssql.sql_recompilations_sec"]',
    unit: "/sec",
    warn: { op: "gt", value: 10, note: "частые recompile" },
  },
  {
    id: "mssql.user_connections",
    source: "mssql",
    group: "General Statistics",
    name: "User Connections",
    description: "Текущие пользовательские соединения. Рост без пула — риск исчерпания worker'ов.",
    perfmonPath: "\\SQLServer:General Statistics\\User Connections",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:General Statistics\\User Connections"]`,
    zabbixOfficialKey: "mssql.user_connections",
    jsonPath: '$.values["mssql.user_connections"]',
    unit: "count",
  },
  {
    id: "mssql.processes_blocked",
    source: "mssql",
    group: "General Statistics",
    name: "Processes blocked",
    description: "Сейчас заблокированные процессы. Ноль — блокировок нет; любое устойчивое значение — разбирать wait/blocking.",
    perfmonPath: "\\SQLServer:General Statistics\\Processes blocked",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:General Statistics\\Processes blocked"]`,
    zabbixOfficialKey: "mssql.processes_blocked",
    jsonPath: '$.values["mssql.processes_blocked"]',
    unit: "count",
    warn: { op: "gt", value: 0, note: "есть блокировки" },
  },
  {
    id: "mssql.logins_sec",
    source: "mssql",
    group: "General Statistics",
    name: "Logins/sec",
    description: "Новые логины в секунду (без pooled reuse). Высокое значение — слабый connection pooling.",
    perfmonPath: "\\SQLServer:General Statistics\\Logins/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:General Statistics\\Logins/sec"]`,
    zabbixOfficialKey: "mssql.logins_sec.rate",
    jsonPath: '$.values["mssql.logins_sec"]',
    unit: "/sec",
    warn: { op: "gt", value: 2, note: "пул соединений, скорее всего, не работает" },
  },
  {
    id: "mssql.total_server_memory_kb",
    source: "mssql",
    group: "Memory Manager",
    name: "Total Server Memory",
    description: "Память, которую SQL Server уже взял. Сравнивайте с Target: если Total << Target, инстанс ещё разгоняется или память отбирают.",
    perfmonPath: "\\SQLServer:Memory Manager\\Total Server Memory (KB)",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Memory Manager\\Total Server Memory (KB)"]`,
    zabbixOfficialKey: "mssql.total_server_memory",
    jsonPath: '$.values["mssql.total_server_memory_kb"]',
    unit: "KB",
  },
  {
    id: "mssql.target_server_memory_kb",
    source: "mssql",
    group: "Memory Manager",
    name: "Target Server Memory",
    description: "Сколько памяти SQL Server хочет потребить.",
    perfmonPath: "\\SQLServer:Memory Manager\\Target Server Memory (KB)",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Memory Manager\\Target Server Memory (KB)"]`,
    zabbixOfficialKey: "mssql.target_server_memory",
    jsonPath: '$.values["mssql.target_server_memory_kb"]',
    unit: "KB",
  },
  {
    id: "mssql.memory_grants_pending",
    source: "mssql",
    group: "Memory Manager",
    name: "Memory Grants Pending",
    description: "Запросы, ждущие workspace memory (hash/sort). Любое значение > 0 — нехватка памяти запросов.",
    perfmonPath: "\\SQLServer:Memory Manager\\Memory Grants Pending",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Memory Manager\\Memory Grants Pending"]`,
    zabbixOfficialKey: "mssql.memory_grants_pending",
    jsonPath: '$.values["mssql.memory_grants_pending"]',
    unit: "count",
    warn: { op: "gt", value: 0, note: "запросы ждут память" },
  },
  {
    id: "mssql.lock_waits_sec",
    source: "mssql",
    group: "Locks",
    name: "Lock Waits/sec",
    description: "Запросы блокировок, которые ждали. Ноль — блокировок нет.",
    perfmonPath: "\\SQLServer:Locks(_Total)\\Lock Waits/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Locks(_Total)\\Lock Waits/sec"]`,
    zabbixOfficialKey: "mssql.lock_waits_sec.rate",
    jsonPath: '$.values["mssql.lock_waits_sec"]',
    unit: "/sec",
    warn: { op: "gt", value: 0, note: "есть ожидания блокировок" },
  },
  {
    id: "mssql.deadlocks_sec",
    source: "mssql",
    group: "Locks",
    name: "Number of Deadlocks/sec",
    description: "Взаимоблокировки. Должны быть нулём.",
    perfmonPath: "\\SQLServer:Locks(_Total)\\Number of Deadlocks/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Locks(_Total)\\Number of Deadlocks/sec"]`,
    zabbixOfficialKey: "mssql.number_deadlocks_sec.rate",
    jsonPath: '$.values["mssql.deadlocks_sec"]',
    unit: "/sec",
    warn: { op: "gt", value: 0, note: "есть deadlock" },
  },
  {
    id: "mssql.full_scans_sec",
    source: "mssql",
    group: "Access Methods",
    name: "Full Scans/sec",
    description: "Полные сканы таблиц/индексов. Для OLTP сравнивайте с Index Searches/sec (ориентир 1 скан на 1000 поисков).",
    perfmonPath: "\\SQLServer:Access Methods\\Full Scans/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Access Methods\\Full Scans/sec"]`,
    zabbixOfficialKey: "mssql.full_scans_sec.rate",
    jsonPath: '$.values["mssql.full_scans_sec"]',
    unit: "/sec",
  },
  {
    id: "mssql.index_searches_sec",
    source: "mssql",
    group: "Access Methods",
    name: "Index Searches/sec",
    description: "Поиски по индексу. Предпочтительнее full scan.",
    perfmonPath: "\\SQLServer:Access Methods\\Index Searches/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Access Methods\\Index Searches/sec"]`,
    zabbixOfficialKey: "mssql.index_searches_sec.rate",
    jsonPath: '$.values["mssql.index_searches_sec"]',
    unit: "/sec",
  },
  {
    id: "mssql.page_splits_sec",
    source: "mssql",
    group: "Access Methods",
    name: "Page Splits/sec",
    description: "Разбиения страниц индекса при вставках. Высокое значение — фрагментация, fillfactor.",
    perfmonPath: "\\SQLServer:Access Methods\\Page Splits/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Access Methods\\Page Splits/sec"]`,
    zabbixOfficialKey: "mssql.page_splits_sec.rate",
    jsonPath: '$.values["mssql.page_splits_sec"]',
    unit: "/sec",
  },
  {
    id: "mssql.latch_waits_sec",
    source: "mssql",
    group: "Latches",
    name: "Latch Waits/sec",
    description: "Ожидания latch (лёгкие блокировки памяти). Рост вместе с I/O — давление на buffer pool.",
    perfmonPath: "\\SQLServer:Latches\\Latch Waits/sec",
    zabbixPerfKey: `perf_counter_en["\\SQLServer:Latches\\Latch Waits/sec"]`,
    zabbixOfficialKey: "mssql.latch_waits_sec.rate",
    jsonPath: '$.values["mssql.latch_waits_sec"]',
    unit: "/sec",
  },
];

export const catalogById = Object.fromEntries(catalog.map((m) => [m.id, m]));

export function osCatalog() {
  return catalog.filter((m) => m.source === "os");
}

export function mssqlCatalog() {
  return catalog.filter((m) => m.source === "mssql");
}
